#include <iostream>
using namespace std;
int main(){
    cout<<"Size of char : "<<sizeof(char)<<" byte"<<endl;
    cout<<"Size of short : "<<sizeof(short)<<" bytes"<<endl;
    cout<<"Size of int : "<<sizeof(int)<<" bytes"<<endl;
    cout<<"Size of long : "<<sizeof(long)<<" bytes"<<endl;
    cout<<"Size of long long : "<<sizeof(long long)<<" bytes"<<endl;
    cout<<"Size of float : "<<sizeof(float)<<" bytes"<<endl;
    cout<<"Size of double : "<<sizeof(double)<<" bytes"<<endl;
    cout<<"Size of long double : "<<sizeof(long double)<<" bytes"<<endl;
    cout<<"Size of bool : "<<sizeof(bool)<<" byte"<<endl;
    cout<<"Size of char16_t : "<<sizeof(char16_t)<<" bytes"<<endl;
    cout<<"Size of char32_t : "<<sizeof(char32_t)<<" bytes"<<endl;
    cout<<"Size of wchar_t : "<<sizeof(wchar_t)<<" bytes"<<endl;
    cout<<"Size of int8_t : "<<sizeof(int8_t)<<" bytes"<<endl;
    cout<<"Size of uint8_t : "<<sizeof(uint8_t)<<" bytes"<<endl;
    cout<<"Size of int16_t : "<<sizeof(int16_t)<<" bytes"<<endl;
    cout<<"Size of uint16_t : "<<sizeof(uint16_t)<<" bytes"<<endl;
    cout<<"Size of int32_t : "<<sizeof(int32_t)<<" bytes"<<endl;
    cout<<"Size of uint32_t : "<<sizeof(uint32_t)<<" bytes"<<endl;
    cout<<"Size of int64_t : "<<sizeof(int64_t)<<" bytes"<<endl;
    cout<<"Size of uint64_t : "<<sizeof(uint64_t)<<" bytes"<<endl;
    cout<<"Size of int_least8_t : "<<sizeof(int_least8_t)<<" bytes"<<endl;
    cout<<"Size of uint_least8_t : "<<sizeof(uint_least8_t)<<" bytes"<<endl;
    cout<<"Size of int_least16_t : "<<sizeof(int_least16_t)<<" bytes"<<endl;
    cout<<"Size of uint_least16_t : "<<sizeof(uint_least16_t)<<" bytes"<<endl;
    cout<<"Size of int_least32_t : "<<sizeof(int_least32_t)<<" bytes"<<endl;
    cout<<"Size of uint_least32_t : "<<sizeof(uint_least32_t)<<" bytes"<<endl;
    cout<<"Size of int_least64_t : "<<sizeof(int_least64_t)<<" bytes"<<endl;
    cout<<"Size of uint_least64_t : "<<sizeof(uint_least64_t)<<" bytes"<<endl;
    cout<<"Size of int_fast8_t : "<<sizeof(int_fast8_t)<<" bytes"<<endl;
    cout<<"Size of uint_fast8_t : "<<sizeof(uint_fast8_t)<<" bytes"<<endl;
    cout<<"Size of int_fast16_t : "<<sizeof(int_fast16_t)<<" bytes"<<endl;
    cout<<"Size of uint_fast16_t : "<<sizeof(uint_fast16_t)<<" bytes"<<endl;
    cout<<"Size of int_fast32_t : "<<sizeof(int_fast32_t)<<" bytes"<<endl;
    cout<<"Size of uint_fast32_t : "<<sizeof(uint_fast32_t)<<" bytes"<<endl;
    cout<<"Size of int_fast64_t : "<<sizeof(int_fast64_t)<<" bytes"<<endl;
    cout<<"Size of uint_fast64_t : "<<sizeof(uint_fast64_t)<<" bytes"<<endl;
    cout<<"Size of intptr_t : "<<sizeof(intptr_t)<<" bytes"<<endl;
    cout<<"Size of uintptr_t : "<<sizeof(uintptr_t)<<" bytes"<<endl;
    cout<<"Size of intmax_t : "<<sizeof(intmax_t)<<" bytes"<<endl;
    cout<<"Size of uintmax_t : "<<sizeof(uintmax_t)<<" bytes"<<endl;
    cout<<"Size of size_t : "<<sizeof(size_t)<<" bytes"<<endl;
    cout<<"Size of ptrdiff_t : "<<sizeof(ptrdiff_t)<<" bytes"<<endl;
    return 0;
}